@startuml test


class Product {
    + name : String
    + price : double
}

DiscountCalculator "1" *-- "many" Product

class DiscountCalculator {
    + products : ArrayList<Product>
    ----
    + discountByPercentage(minimumPrice : double, percentage: double) : void
    + addFreeCompanyGlass(minimumPrice : double) : void
    + threeForPriceOfTwo() : void
}

class ProductsSorter {
    ----
    + {static}  sort(products : ArrayList<Product>) : ArrayList<Product>
    + {static}  mostExpensive(products : ArrayList<Product>) : Product
    + {static}  theCheapest(products : ArrayList<Product>) : Product
    + {static}  theCheapest(products : ArrayList<Product>, n : int) : ArrayList<Product>
}

@enduml